/**
 * Fixed IPC channel names. Kept dependency-free so the sandboxed Preload can
 * import them without pulling validation libraries into its bundle.
 */
export const IPC_CHANNELS = {
  bootState: 'shell:boot-state',
  chooseProject: 'project:choose',
  offerProject: 'project:offer',
  listProjects: 'project:list',
  removeProject: 'project:remove',
  listSkills: 'skill:list',
  listModels: 'model:list',
  trustProjectSkills: 'skill:trust-project',
  listStandingApprovals: 'approval:list',
  revokeStandingApproval: 'approval:revoke',
  initializeProject: 'project:init',
  confirmProject: 'project:confirm',
  startSession: 'session:start',
  resumeWorktreeBootstrap: 'session:resume-worktree-bootstrap',
  listSessions: 'session:list',
  listDamagedSessions: 'session:list-damaged',
  queryMailbox: 'mailbox:query',
  setSessionPinned: 'session:set-pinned',
  setSessionArchived: 'session:set-archived',
  renameSession: 'session:rename',
  deleteSession: 'session:delete',
  getAppearanceSettings: 'appearance:get-settings',
  setAppearanceSettings: 'appearance:set-settings',
  themeChanged: 'theme:changed',
  getQuitWarningPreference: 'quit-warning:get-preference',
  setQuitWarningPreference: 'quit-warning:set-preference',
  respondToQuitRequest: 'quit-warning:respond',
  quitRequested: 'quit-warning:requested',
  undoShortcut: 'shortcut:undo',
  toggleSidebarShortcut: 'shortcut:toggle-sidebar',
  getReadiness: 'readiness:get',
  refreshReadiness: 'readiness:refresh',
  chooseHarnessExecutable: 'readiness:choose-executable',
  clearHarnessExecutable: 'readiness:clear-executable',
  setLoginShellDiscovery: 'readiness:set-login-shell-discovery',
  openExternalLink: 'shell:open-external-link',
  preparePullRequest: 'pull-request:prepare',
  createPullRequest: 'pull-request:create',
  openPullRequest: 'pull-request:open',
  startRun: 'run:start',
  listRuns: 'run:list',
  stopRun: 'run:stop',
  getCheckoutFacts: 'checkout:facts',
  listBranches: 'checkout:branches',
  listEditors: 'editor:list',
  openInEditor: 'editor:open',
  getConversation: 'conversation:get',
  developSession: 'conversation:develop',
  enqueueQueuedSubmission: 'conversation:queue-enqueue',
  editQueuedSubmission: 'conversation:queue-edit',
  moveQueuedSubmission: 'conversation:queue-move',
  cancelQueuedSubmission: 'conversation:queue-cancel',
  pauseConversationQueue: 'conversation:queue-pause',
  resumeConversationQueue: 'conversation:queue-resume',
  sendQueuedSubmissionNow: 'conversation:queue-send-now',
  resolveApproval: 'conversation:resolve-approval',
  prepareRunUndo: 'run:undo-prepare',
  applyRunUndo: 'run:undo-apply',
  conversationEvent: 'conversation:event',
  openSessionRequest: 'session:open-request'
} as const
