/**
 * Fixed IPC channel names. Kept dependency-free so the sandboxed Preload can
 * import them without pulling validation libraries into its bundle.
 */
export const IPC_CHANNELS = {
  bootState: 'shell:boot-state',
  chooseProject: 'project:choose',
  offerProject: 'project:offer',
  listProjects: 'project:list',
  removeProject: 'project:remove',
  listSkills: 'skill:list',
  listModels: 'model:list',
  trustProjectSkills: 'skill:trust-project',
  listStandingApprovals: 'approval:list',
  revokeStandingApproval: 'approval:revoke',
  initializeProject: 'project:init',
  confirmProject: 'project:confirm',
  startSession: 'session:start',
  listSessions: 'session:list',
  listDamagedSessions: 'session:list-damaged',
  queryMailbox: 'mailbox:query',
  setSessionPinned: 'session:set-pinned',
  setSessionArchived: 'session:set-archived',
  renameSession: 'session:rename',
  deleteSession: 'session:delete',
  setThemePreference: 'theme:set-preference',
  themeChanged: 'theme:changed',
  undoShortcut: 'shortcut:undo',
  getReadiness: 'readiness:get',
  refreshReadiness: 'readiness:refresh',
  chooseHarnessExecutable: 'readiness:choose-executable',
  clearHarnessExecutable: 'readiness:clear-executable',
  setLoginShellDiscovery: 'readiness:set-login-shell-discovery',
  openExternalLink: 'shell:open-external-link',
  startRun: 'run:start',
  listRuns: 'run:list',
  stopRun: 'run:stop',
  getCheckoutFacts: 'checkout:facts',
  listBranches: 'checkout:branches',
  listEditors: 'editor:list',
  openInEditor: 'editor:open',
  getConversation: 'conversation:get',
  developSession: 'conversation:develop',
  resolveApproval: 'conversation:resolve-approval',
  conversationEvent: 'conversation:event',
  openSessionRequest: 'session:open-request'
} as const
